# Generated by Django 2.2.3 on 2019-10-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=60)),
                ('mobno', models.CharField(max_length=10)),
                ('comments', models.CharField(max_length=600)),
            ],
        ),
    ]
