# Generated by Django 2.2.3 on 2019-10-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnotes', '0002_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Post',
        ),
    ]
